import {StyleSheet} from 'react-native';
export const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#070b10',
    paddingHorizontal: 48,
    paddingTop: 26,
  },
  header: {
    height: 82,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1b2632',
    gap: 25,
  },
  brand: {flexDirection: 'row', alignItems: 'center', gap: 15, width: 355},
  brandIcon: {
    width: 56,
    height: 56,
    backgroundColor: '#143428',
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#226a4d',
  },
  brandPlane: {fontSize: 34, color: '#25df9b', transform: [{rotate: '-30deg'}]},
  brandName: {
    color: '#edf4f9',
    fontSize: 30,
    fontWeight: '700',
    letterSpacing: 1,
  },
  brandSub: {fontSize: 10, letterSpacing: 2.2, color: '#7a928a', marginTop: 5},
  tabs: {flexDirection: 'row', flex: 1, justifyContent: 'center', gap: 8},
  tab: {
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    paddingHorizontal: 24,
  },
  titlebar: {
    height: 108,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 38,
    fontWeight: '600',
    letterSpacing: -0.7,
    color: '#eef3f7',
  },
  subtitle: {fontSize: 18, color: '#8294a5', marginTop: 9},
  statusPill: {alignItems: 'flex-end'},
  statusText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#25df9b',
    letterSpacing: 1.5,
  },
  statusSub: {fontSize: 17, color: '#8395a5', marginTop: 8},
  error: {fontSize: 18, color: '#ffb08b', marginBottom: 15},
  layout: {flex: 1, flexDirection: 'row', gap: 26, minHeight: 0},
  left: {flex: 1, minWidth: 0},
  right: {width: 570},
  toolbar: {flexDirection: 'row', gap: 12, marginBottom: 16},
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    borderColor: '#26313c',
    borderWidth: 1,
    borderRadius: 30,
    alignItems: 'center',
    paddingHorizontal: 18,
    backgroundColor: '#0e151e',
  },
  searchIcon: {color: '#92a69c', fontSize: 29, marginRight: 12},
  search: {flex: 1, color: '#e2ebe7', fontSize: 19, paddingVertical: 14},
  mapControls: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 15,
    alignItems: 'center',
  },
  mapCount: {flex: 1, textAlign: 'right', color: '#8fa79c', fontSize: 17},
  nearbyTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 10,
  },
  sectionTitle: {fontSize: 23, color: '#e1eaf2', fontWeight: '600'},
  subtle: {fontSize: 17, color: '#8b9dab', marginTop: 5},
  nearby: {flexGrow: 0, height: 115},
  aircraftCard: {
    width: 320,
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  cardTop: {flexDirection: 'row', alignItems: 'center', gap: 10},
  cardPlane: {fontSize: 26, color: '#eab755'},
  cardCallsign: {fontSize: 23, color: '#e5eef2', fontWeight: '600'},
  cardDistance: {fontSize: 16, color: '#23d896', flex: 1, textAlign: 'right'},
  cardOperator: {fontSize: 17, color: '#899eae', marginTop: 11},
  cardMetrics: {fontSize: 17, color: '#bac8d2', marginTop: 9},
  footer: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
  },
  footerText: {fontSize: 13, letterSpacing: 0.8, color: '#6f8393'},
  footerTime: {fontSize: 19, color: '#b7c5cd'},
  toast: {
    position: 'absolute',
    bottom: 85,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 22,
    alignItems: 'center',
    backgroundColor: '#143c2e',
    borderWidth: 1,
    borderColor: '#28c990',
    borderRadius: 18,
    padding: 20,
    maxWidth: 1200,
  },
  toastText: {fontSize: 22, color: '#caffdf'},
  widePanel: {
    flex: 1,
    backgroundColor: '#0e1620',
    borderWidth: 1,
    borderColor: '#23313e',
    borderRadius: 22,
    padding: 32,
  },
  infoPanel: {
    width: 490,
    backgroundColor: '#0e191c',
    borderWidth: 1,
    borderColor: '#234237',
    borderRadius: 22,
    padding: 38,
    gap: 24,
  },
  eyebrow: {color: '#20d894', fontSize: 15, letterSpacing: 2.5},
  panelTitle: {
    fontSize: 31,
    fontWeight: '600',
    color: '#e7f0f5',
    lineHeight: 40,
  },
  panelHint: {fontSize: 19, lineHeight: 29, color: '#8fa3b1', marginTop: 8},
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    padding: 23,
    marginBottom: 12,
    gap: 25,
  },
  direction: {fontSize: 28, color: '#25df9b', width: 62},
  rowTitle: {fontSize: 25, color: '#e2edf3', fontWeight: '600'},
  rowValue: {fontSize: 25, color: '#23de98', textAlign: 'right'},
  hugeIcon: {fontSize: 100, color: '#1fbc84'},
  bigStat: {
    fontSize: 92,
    color: '#24df9b',
    fontWeight: '500',
    letterSpacing: -4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ruleBar: {flexDirection: 'row', gap: 12, marginVertical: 15},
  ruleInput: {
    flex: 1,
    fontSize: 22,
    padding: 18,
    borderColor: '#345247',
    borderWidth: 2,
    borderRadius: 12,
    color: '#ecf5ef',
  },
  savedRow: {
    flexDirection: 'row',
    gap: 18,
    alignItems: 'center',
    borderTopColor: '#24333f',
    borderTopWidth: 1,
    paddingVertical: 24,
  },
  greenText: {fontSize: 22, color: '#20d995'},
  empty: {fontSize: 22, color: '#8fa6b3', paddingVertical: 35, lineHeight: 34},
  emptyLog: {alignItems: 'center', padding: 50, gap: 20},
  coverageStat: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: '#284036',
    borderBottomWidth: 1,
    paddingBottom: 20,
  },
});
