name: Docs Lint

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'overrides/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-lint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    uses: willtheorangeguy/mkdocs/.github/workflows/docs-lint.yml@main
