name: Docs

on:
  push:
    branches: [main, master]
    paths:
      - 'docs/**'
      - 'overrides/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'LICENSE.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    uses: willtheorangeguy/mkdocs/.github/workflows/docs-build.yml@main
